// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ProTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new EdgeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pro() {
    driver.get("http://peiyin.xunfei.cn/make/");
    driver.manage().window().setSize(new Dimension(1053, 848));
    List<WebElement> all2 = driver.findElements(By.cssSelector(".multiple-speed-feild"));
    {
      for (WebElement e : all2) {
        if (e.getText().equals(".multiple-speed-feild")) {
          e.click();
        }
      }
    } List<WebElement> all3 = driver.findElements(By.cssSelector(".custom_global > img"));
    { for (WebElement M: all3){

      Actions builder = new Actions(driver);
      builder.moveToElement(M).perform();
    }}
    List<WebElement> all14 = driver.findElements(By.id("markeditor"));
    for(WebElement e:all14){
      if(e.getText().equals("markeditor")){
        e.click();
      }
    }
    List<WebElement> all24 = driver.findElements(By.cssSelector(".tts-editor-root"));
    for(WebElement e:all24){
      if(e.getText().equals(".tts-editor-root")){
        e.click();
      }
    }


    {   List<WebElement> all27 = driver.findElements(By.id("markeditor"));
      for(WebElement e:all27){
        if(e.getText().equals("markeditor")){
          js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"tts-content-paragraph\">Youth is not a time of life; it is a state of mind; it is not a matter of rosy cheeks, red lips and supple knees; it is a matter of the will, a quality of the imagination, a vigor of the emotions; it is the freshness of the deep springs of life.</p><p class=\"tts-content-paragraph\">Youth means a temperamental predominance of courage over timidity, of the appetite for adventure over the love of ease. This often exists in a man of 60 more than a boy of 20. Nobody grows old merely by a number of years. We grow old by deserting our ideals.</p><p class=\"tts-content-paragraph\">Years may wrinkle the skin, but to give up enthusiasm wrinkles&nbsp;</p>'}", e);

        }
      }


    }
    List<WebElement> all27 = driver.findElements(By.cssSelector(".tts-play-toggle"));
    for(WebElement e:all27){
      if(e.getText().equals("markeditor")){
        js.executeScript("window.scrollTo(0,0)");
      }
    }

    ;
    {
      List<WebElement> all29 = driver.findElements(By.cssSelector(".multiple-speed-feild"));
      for(WebElement e:all27){
        if(e.getText().equals(".multiple-speed-feild")){

      WebElement element = driver.findElement(By.cssSelector(".multiple-speed-feild"));
      Actions builder = new Actions(driver);
          builder.moveToElement(element).perform();
    }}}


    {
      List<WebElement> all29 = driver.findElements(By.cssSelector(".multiple-speed-feild"));
      for(WebElement e:all27){
        if(e.getText().equals(".multiple-speed-feild")){

          WebElement element = driver.findElement(By.cssSelector(".multiple-speed-feild"));
          Actions builder = new Actions(driver);
          builder.moveToElement(element).release().perform();

        }}

    }
    {List<WebElement> all1 = driver.findElements(By.cssSelector(".multiple-speed-feild"));
      for(WebElement e:all1){
        if(e.getText().equals(".multiple-speed-feild")){
          e.sendKeys("168");
        }
      }

    }
    List<WebElement> all1 = driver.findElements(By.cssSelector(".multiple-speed-feild"));
    for(WebElement e:all1){
      if(e.getText().equals(".multiple-speed-feild")){
        e.click();
      }
    }
    List<WebElement> allK = driver.findElements(By.cssSelector(".multiple-speed-feild"));
    {  for(WebElement e:all1){
      if(e.getText().equals(".multiple-speed-feild")){
        Actions builder = new Actions(driver);
        builder.moveToElement(e).clickAndHold().perform();
        builder.moveToElement(e).perform();
        builder.moveToElement(e).release().perform();
      }
    }


    }



    List<WebElement> alls = driver.findElements(By.cssSelector(".multiple-intonation-feild"));
    for(WebElement e:alls){
      if(e.getText().equals(".multiple-intonation-feild")){
        driver.findElement(By.cssSelector(".multiple-intonation-feild")).sendKeys("74");
        e.click();
        Actions builder = new Actions(driver);
        builder.moveToElement(e).clickAndHold().perform();
        builder.moveToElement(e).perform();
        builder.moveToElement(e).release().perform();
      }
    }


    List<WebElement> all11 = driver.findElements(By.cssSelector(".multiple-intonation-feild"));
    for(WebElement e:all1){
      if(e.getText().equals(".multiple-intonation-feild")){
        driver.findElement(By.cssSelector(".multiple-intonation-feild")).sendKeys("85");
        e.click();
        Actions builder = new Actions(driver);
        builder.moveToElement(e).clickAndHold().perform();
        builder.moveToElement(e).perform();
        builder.moveToElement(e).release().perform();
      }
    }



    for(WebElement e:all1){
      if(e.getText().equals(".multiple-intonation-feild")){
        driver.findElement(By.cssSelector(".multiple-intonation-feild")).sendKeys("85");
        e.click();
      }
    }

    {
      for(WebElement E:all1){
        if(E.getText().equals(".multiple-intonation-feild")){

      Actions builder = new Actions(driver);
      builder.moveToElement(E).clickAndHold().perform();
      builder.moveToElement(E).perform();
      builder.moveToElement(E).release().perform();
    }}}

    List<WebElement> all12 = driver.findElements(By.cssSelector(".multiple-intonation-feild"));
    for(WebElement e:all1){
      if(e.getText().equals(".multiple-intonation-feild")){
        driver.findElement(By.cssSelector(".multiple-intonation-feild")).sendKeys("65");
        e.click();
      }
    }



    List<WebElement> all13 = driver.findElements(By.cssSelector(".multiple-editor-wrapper"));
    for(WebElement e:all1){
      if(e.getText().equals(".multiple-editor-wrapper")){

        e.click();
      }
    }

    js.executeScript("window.scrollTo(0,119.19999694824219)");
    List<WebElement> all100 = driver.findElements(By.xpath("//div[@id=\'multiple\']/div/div[2]/div[3]"));
    for(WebElement e:all100){
      if(e.getText().equals("//div[@id=\'multiple\']/div/div[2]/div[3]")){
        e.click();
      }
    }


    {  List<WebElement> all101 = driver.findElements(By.id("markeditor"));
      for(WebElement e:all101){
      if(e.getText().equals("markeditor")){
        js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"tts-content-paragraph\">你好最近怎么样，在干旱蚂</p>'}", e);
        js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"tts-content-paragraph\">你好最近怎么样，在干旱</p>'}", e);
        js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"tts-content-paragraph\">你好最近怎么样，在干</p>'}", e);
        js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"tts-content-paragraph\">你好最近怎么样，在干嘛呀 有什么问题</p>'}", e);
        js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"tts-content-paragraph\">你好最近怎么样，在干嘛呀 有什么问题吗 最近还是在干嘛</p>'}", e);
      }}}




    {


    }



    {  List<WebElement> all23 = driver.findElements((By.linkText("多人播报配音")));
      for(WebElement e:all23){
        if(e.getText().equals("多人播报配音")){
          Actions builder = new Actions(driver);
          builder.moveToElement(e).perform();

        }
      }

    }
    List<WebElement> all15 = driver.findElements(By.cssSelector(".tts-play-toggle"));
    for(WebElement e:all1){
      if(e.getText().equals(".tts-play-toggle")){
        e.click();
      }
    }



  }
}
