// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProjecttestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {

      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void projecttest() {
    driver.get("https://ai.youdao.com/product-fanyi-text.s");
    driver.manage().window().setSize(new Dimension(1536, 864));
    driver.findElement(By.id("inputText")).click();
    driver.findElement(By.id("inputText")).sendKeys("今天吃了什么，然后今天做了什么，有没有好好吃饭或作业写好没有，我今天完成了很多任务比如说 有测试软件功能的好坏以及很多很多事业上的事情，这样可以很快地让我完成所有的作业，我并不知道我要干什么");
    driver.findElement(By.id("translateBtn")).click();
    driver.findElement(By.id("customSelectBtn")).click();
    driver.findElement(By.id("inputText")).click();
    driver.findElement(By.id("outputMod")).click();
    driver.findElement(By.id("clearInput")).click();
    driver.findElement(By.id("inputText")).click();
    driver.findElement(By.id("inputText")).sendKeys("What did I eat today, what did I do today, did I have a good meal or did I finish my homework? I finished a lot of tasks today, such as testing the function of the software and many, many career things, so that I can quickly finish all the homework, I don\'t know what I am going to do");
    driver.findElement(By.id("translateBtn")).click();
    driver.findElement(By.id("customSelectBtn")).click();
    driver.findElement(By.cssSelector(".tgt")).click();
    driver.findElement(By.id("clearInput")).click();
    driver.findElement(By.id("inputText")).click();
    driver.findElement(By.id("inputText")).sendKeys("我今天吃了什么，我今天做了什么，我吃得好吗，我完成作业了吗?我今天完成了很多任务，比如测试软件的功能和很多很多的事业上的事情，这样我就可以快速完成所有的作业，我不知道我要做什么");
    driver.findElement(By.id("customSelectBtn")).click();
    driver.findElement(By.linkText("中文  »  法语")).click();
    driver.findElement(By.id("translateBtn")).click();
    driver.findElement(By.id("outputMod")).click();
    driver.findElement(By.id("clearInput")).click();
    driver.findElement(By.id("inputText")).click();
    driver.findElement(By.id("inputText")).sendKeys("Qu’est-ce que j’ai mangé aujourd’hui? Qu’est-ce que j’ai fait aujourd’hui? Ai-je bien mangé? Ai-je terminé Mes Devoirs? J’ai fait beaucoup de tâches aujourd’hui, comme tester les fonctionnalités du logiciel et beaucoup, beaucoup de choses professionnelles afin que je puisse faire tous Mes Devoirs rapidement. Je ne sais pas ce que je vais faire");
    driver.findElement(By.id("customSelectBtn")).click();
    driver.findElement(By.linkText("自动检测语言")).click();
    driver.findElement(By.id("translateBtn")).click();
    driver.findElement(By.id("clearInput")).click();
    driver.findElement(By.id("tran-type")).click();
    driver.findElement(By.id("inputText")).click();
    driver.findElement(By.cssSelector(".selector")).click();
    driver.findElement(By.id("tran-type")).click();
    {
      WebElement dropdown = driver.findElement(By.id("tran-type"));
       dropdown.findElement(By.xpath("//option[. = '文档翻译']")).click();
    }
    driver.findElement(By.linkText("立即体验")).click();
    List<WebElement> all1 = driver.findElements(By.id("uploadDocs_btn"));
    for(WebElement e:all1){
      if(e.getText().equals("uploadDocs_btn")){

        e.click();
      }
    }

    vars.put("window_handles", driver.getWindowHandles());
    List<WebElement> all2 = driver.findElements(By.cssSelector(".item-content:nth-child(1) > .list-content:nth-child(4) > .list-text"));
    for(WebElement e:all1){
      if(e.getText().equals(".item-content:nth-child(1) > .list-content:nth-child(4) > .list-text")){
        e.click();
      }
    }


    vars.put("win2472", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win2472").toString());
    List<WebElement> all3 = driver.findElements(By.id("local-upload4"));
    for(WebElement e:all1){
      if(e.getText().equals("local-upload4")){
        e.click();
      }
    }

    List<WebElement> all4 = driver.findElements(By.id("upload-file-input4"));
    for(WebElement e:all1){
      if(e.getText().equals("upload-file-input4")){
        driver.findElement(By.id("upload-file-input4")).sendKeys("C:\\fakepath\\db205f398ded0b388ccfe3ab8f772ced.jpeg");
      }
    }
    List<WebElement> all5 = driver.findElements(By.id("local-upload4"));
    for(WebElement e:all1){
      if(e.getText().equals("local-upload4")){
      e.click();
      }
    }
    List<WebElement> all6 = driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(2) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(2) > img")){
        e.click();
      }
    }
    List<WebElement> all7 = driver.findElements(By.cssSelector(".selli"));
    for(WebElement e:all1){
      if(e.getText().equals(".selli")){
        e.click();
      }
    }

    List<WebElement> all8= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(4) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(4) > img")){
        e.click();
      }
    }
    List<WebElement> all9= driver.findElements(By.id("onlinetext4"));
    for(WebElement e:all1){
      if(e.getText().equals("onlinetext4")){
        e.click();
      }
    }
    List<WebElement> all10= driver.findElements(By.id("local-upload4"));
    for(WebElement e:all1){
      if(e.getText().equals("local-upload4")){
        e.click();
      }
    }
    List<WebElement> all11= driver.findElements(By.id("upload-file-input4"));
    for(WebElement e:all1){
      if(e.getText().equals("upload-file-input4")){
        driver.findElement(By.id("upload-file-input4")).sendKeys("C:\\fakepath\\a8014c086e061d950a7b88e606bc1dd162d9f3d35c9e.jpg");
      }
    }


    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win2472").toString());
    vars.put("window_handles", driver.getWindowHandles());
    List<WebElement> all12= driver.findElements(By.linkText("语音合成"));
    for(WebElement e:all1){
      if(e.getText().equals("语音合成")){
        e.click();
      }
    }

    vars.put("win3797", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3797").toString());
    List<WebElement> all13= driver.findElements(By.id("inputText"));
    for(WebElement e:all1){
      if(e.getText().equals("inputText")){
        e.click();
        driver.findElement(By.id("inputText")).sendKeys("你好今天吃了什么，你下午有空参加我们的活动吗？ 如果有的话请一定要提前告诉我们行不行， please talk to me , and ");
        driver.switchTo().frame(1);
      }
    }


    List<WebElement> all14= driver.findElements(By.id("phoneipt"));
    for(WebElement e:all1){
      if(e.getText().equals("phoneipt")){
        driver.findElement(By.id("phoneipt")).sendKeys("ia");
      }
    }

    driver.switchTo().defaultContent();
    List<WebElement> all15= driver.findElements(By.id("inputText"));
    for(WebElement e:all1){
      if(e.getText().equals("inputText")){
        e.click();
        driver.findElement(By.id("inputText")).sendKeys("你好今天吃了什么，你下午有空参加我们的活动吗？ 如果有的话请一定要提前告诉我们行不行， please talk to me , and I want to ask how mant peple will attend this party?");
      }
    }

    List<WebElement> all16= driver.findElements(By.id("syntheticBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("syntheticBtn")){
        e.click();

      }
    }
    List<WebElement> all17= driver.findElements(By.id("customSelectBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("customSelectBtn")){
        e.click();

      }
    }
    List<WebElement> all18= driver.findElements(By.linkText("中文"));
    for(WebElement e:all1){
      if(e.getText().equals("中文")){
        e.click();

      }
    }
    List<WebElement> all19= driver.findElements(By.id("syntheticBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("syntheticBtn")){
        e.click();

      }
    }
    List<WebElement> all20= driver.findElements(By.id("customSelectChineseBtnPitch"));
    for(WebElement e:all1){
      if(e.getText().equals("customSelectChineseBtnPitch")){
        e.click();

      }
    }
    List<WebElement> all21= driver.findElements(By.linkText("男声"));
    for(WebElement e:all1){
      if(e.getText().equals("男声")){
        e.click();

      }
    }
    List<WebElement> all22= driver.findElements(By.linkText("syntheticBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("syntheticBtn")){
        e.click();

      }
    }

    List<WebElement> all23= driver.findElements(By.id("inputText"));
    for(WebElement e:all1){
      if(e.getText().equals("inputText")){
        driver.findElement(By.id("inputText")).sendKeys("你好今天吃了什么，你下午有空参加我们的活动吗？ 如果有的话请一定要提前告诉我们行不行， please talk to me , and I want to ask how many people will attend this party?");

      }
    }
    List<WebElement> all24= driver.findElements(By.id("customSelectBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("customSelectBtn")){
       e.click();

      }
    }

    List<WebElement> all25= driver.findElements(By.linkText("自动识别"));
    for(WebElement e:all1){
      if(e.getText().equals("自动识别")){
        e.click();

      }
    }
    List<WebElement> all26= driver.findElements(By.linkText("自动识别"));
    for(WebElement e:all1) {
      if (e.getText().equals("自动识别")) {
        e.click();

      }
    }
      List<WebElement>all27= driver.findElements(By.id("syntheticBtn"));
      for(WebElement m:all1){
        if(m.getText().equals("syntheticBtn")){
          m.click();

        }}
        List<WebElement>all28= driver.findElements(By.id("syntheticBtn"));
        for(WebElement e:all1){
          if(e.getText().equals("syntheticBtn")){
            e.click();

          } }
    List<WebElement>all29= driver.findElements(By.id("customSelectBtnText"));
    for(WebElement e:all1){
      if(e.getText().equals("customSelectBtnText")){
        e.click();

      } }
    List<WebElement>all30= driver.findElements(By.id("韩文"));
    for(WebElement e:all1){
      if(e.getText().equals("韩文")){
        e.click();

      } }
    List<WebElement>all31= driver.findElements(By.id("syntheticBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("syntheticBtn")){
        e.click();

      } }
    List<WebElement>all32= driver.findElements(By.id("tran-type"));
    for(WebElement e:all1){
      if(e.getText().equals("tran-type")){
        e.click();

      } }


    {
      List<WebElement>all33= driver.findElements(By.id("tran-type"));
      for(WebElement e:all1){
        if(e.getText().equals("tran-type")){
          WebElement dropdown = driver.findElement(By.id("tran-type"));
          dropdown.findElement(By.xpath("//option[. = '语音评测']")).click();
        } }


    }
    List<WebElement>all33= driver.findElements(By.id("inputTextAssess"));
    for(WebElement e:all1){
      if(e.getText().equals("inputTextAssess")){
        e.click();

      } }
    List<WebElement>all34= driver.findElements(By.cssSelector(".myRecord_text"));
    for(WebElement e:all1){
      if(e.getText().equals(".myRecord_text")){
        e.click();

      } }

    {
      List<WebElement>all35= driver.findElements(By.cssSelector(".myRecord_text"));
      for(WebElement e:all1){
        if(e.getText().equals(".myRecord_text")){
          WebElement element = driver.findElement(By.cssSelector(".myRecord_text"));
          Actions builder = new Actions(driver);
          builder.moveToElement(element).perform();
        } }

    }
    {
      List<WebElement>all36= driver.findElements(By.cssSelector("body"));
      for(WebElement e:all1){
        if(e.getText().equals(".myRecord_text")){
          WebElement element = driver.findElement(By.cssSelector("body"));
          Actions builder = new Actions(driver);
          builder.moveToElement(element, 0, 0).perform();
        } }

    }
    List<WebElement>all37= driver.findElements(By.id("inputTextAssess"));
    for(WebElement e:all1){
      if(e.getText().equals("inputTextAssess")){
        e.click();
        driver.findElement(By.id("inputTextAssess")).sendKeys("hello how are you recently, i just doing homework now");

      } }
    List<WebElement>all38= driver.findElements(By.cssSelector(".myRecord_text"));
    for(WebElement e:all1){
      if(e.getText().equals(".myRecord_text")){
        e.click();

      } }
    List<WebElement>all39= driver.findElements(By.cssSelector(".right-tab-container"));
    for(WebElement e:all1){
      if(e.getText().equals(".right-tab-container")){
        e.click();

      } }
    List<WebElement>all40= driver.findElements(By.cssSelector(".left-tab-container"));
    for(WebElement e:all1){
      if(e.getText().equals(".left-tab-container")){
        e.click();

      } }

    List<WebElement>all41= driver.findElements(By.id("customSelectBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("customSelectBtn")){
        e.click();

      } }
    List<WebElement>all42= driver.findElements(By.id("inputTextAssess"));
    for(WebElement e:all1){
      if(e.getText().equals("inputTextAssess")){
        e.click();

      } }


    vars.put("window_handles", driver.getWindowHandles());
    List<WebElement>all43= driver.findElements(By.linkText("实时语音识别"));
    for(WebElement e:all1){
      if(e.getText().equals("实时语音识别")){
        e.click();

      } }

    vars.put("win5859", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5859").toString());
    vars.put("window_handles", driver.getWindowHandles());
    List<WebElement>all44= driver.findElements(By.linkText("通用文字识别"));
    for(WebElement e:all1){
      if(e.getText().equals("通用文字识别")){
        e.click();

      } }


    vars.put("win595", waitForWindow(2000));
    driver.switchTo().window(vars.get("win595").toString());
    List<WebElement>all45= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(2) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(2) > img")){
        e.click();

      } }

    List<WebElement>all46= driver.findElements(By.id("local-upload7"));
    for(WebElement e:all1){
      if(e.getText().equals("local-upload7")){
        e.click();

      } }

    List<WebElement>all47= driver.findElements(By.id("upload-file-input7"));
    for(WebElement e:all1){
      if(e.getText().equals("upload-file-input7")){
        driver.findElement(By.id("upload-file-input7")).sendKeys("C:\\fakepath\\db205f398ded0b388ccfe3ab8f772ced.jpeg");

      } }

    List<WebElement>all48= driver.findElements(By.id("local-upload7"));
    for(WebElement e:all1){
      if(e.getText().equals("local-upload7")){
        e.click();

      } }
    List<WebElement>all49= driver.findElements(By.id("upload-file-input7"));
    for(WebElement e:all1){
      if(e.getText().equals("upload-file-input7")){
        driver.findElement(By.id("upload-file-input7")).sendKeys("C:\\fakepath\\黑灰色人物头像创意个人交流中文简历.png");
      } }

    List<WebElement>all50= driver.findElements(By.id("tran-type"));
    for(WebElement e:all1){
      if(e.getText().equals("tran-type")){
        e.click();

      } }


    List<WebElement>all51= driver.findElements(By.id("tran-type"));
    for(WebElement e:all1){
      if(e.getText().equals("tran-type")) {
        WebElement dropdown = driver.findElement(By.id("tran-type"));
        dropdown.findElement(By.xpath("//option[. = '通用文字识别']")).click();


      }}
    List<WebElement>all52= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(2) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(2) > img")){
        e.click();

      } }
    List<WebElement>all53= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(3) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(2) > img")){
        e.click();

      } }
    List<WebElement>all54= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(4) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(2) > img")){
        e.click();

      } }
    List<WebElement>all55= driver.findElements(By.id("tran-type"));
    for(WebElement e:all1){
      if(e.getText().equals("tran-type")){
        e.click();

      } }
    List<WebElement>all56= driver.findElements(By.id("tran-type"));
    for(WebElement e:all1){
      if(e.getText().equals("tran-type")){
        WebElement dropdown = driver.findElement(By.id("tran-type"));
        dropdown.findElement(By.xpath("//option[. = '手写体识别']")).click();

      } }
    List<WebElement>all57= driver.findElements(By.id("result-table5"));
    for(WebElement e:all1){
      if(e.getText().equals("result-table5")){
        WebElement element = driver.findElement(By.id("result-table5"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).clickAndHold().perform();

      } }

    List<WebElement>all58= driver.findElements(By.id("result-table5"));
    for(WebElement e:all1){
      if(e.getText().equals("result-table5")){
        WebElement element = driver.findElement(By.id("result-table5"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();

      } }

    List<WebElement>all59= driver.findElements(By.id("result-table5"));
    for(WebElement e:all1){
      if(e.getText().equals("result-table5")){
        WebElement element = driver.findElement(By.id("result-table5"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).release().perform();
      } }
    List<WebElement>all60= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(2) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(2) > img")){
        e.click();

      } }
    List<WebElement>all61= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(3) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(2) > img")){
        e.click();

      } }
    List<WebElement>all62= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(4) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(2) > img")){
        e.click();

      } }
    List<WebElement>all63= driver.findElements(By.id("tran-type"));
    for(WebElement e:all1){
      if(e.getText().equals("tran-type")){
        e.click();

      } }

    List<WebElement>all64= driver.findElements(By.id("tran-type"));
    for(WebElement e:all1){
      if(e.getText().equals("tran-type")) {
        WebElement dropdown = driver.findElement(By.id("tran-type"));
        dropdown.findElement(By.xpath("//option[. = '表格识别']")).click();
      }
    }
    List<WebElement>all65= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(2) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(2) > img")){
        e.click();

      } }

    List<WebElement>all66= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(3) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(3) > img")){
        e.click();

      } }
    List<WebElement>all67= driver.findElements(By.cssSelector("#result-table4 tr:nth-child(3) > td:nth-child(2)"));
    for(WebElement e:all1){
      if(e.getText().equals("#result-table4 tr:nth-child(3) > td:nth-child(2)")){
        e.click();

      } }

    List<WebElement>all68= driver.findElements(By.cssSelector(".demo-card-list > li:nth-child(4) > img"));
    for(WebElement e:all1){
      if(e.getText().equals(".demo-card-list > li:nth-child(4) > img")){
        e.click();

      } }
    List<WebElement>all69= driver.findElements(By.id("tran-type"));
    for(WebElement e:all1){
      if(e.getText().equals("tran-type")){
        e.click();

      } }



    vars.put("window_handles", driver.getWindowHandles());
    List<WebElement>all70= driver.findElements(By.linkText("网页翻译"));
    for(WebElement e:all1){
      if(e.getText().equals("网页翻译")){
        e.click();

      } }


    vars.put("win8639", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8639").toString());
    List<WebElement>all71= driver.findElements(By.id("inputText"));
    for(WebElement e:all1){
      if(e.getText().equals("inputText")){
        e.click();

      } }
    List<WebElement>all72= driver.findElements(By.cssSelector(".for-example"));
    for(WebElement e:all1){
      if(e.getText().equals(".for-example")){
        e.click();

      } }

    List<WebElement>all73= driver.findElements(By.id("inputText"));
    for(WebElement e:all1){
      if(e.getText().equals("inputText")){
        e.click();

      } }

    List<WebElement>all74= driver.findElements(By.cssSelector(".item-clear"));
    for(WebElement e:all1){
      if(e.getText().equals(".item-clear")){
        e.click();

      } }
    List<WebElement>all75= driver.findElements(By.id("inputText"));
    for(WebElement e:all1){
      if(e.getText().equals("inputText")){
        e.click();
        driver.findElement(By.id("inputText")).sendKeys("<link rel=\"stylesheet\" href=\"/common/urs-login-component/main.build.css?timestamp=1669277616120\">");
      } }
    List<WebElement>all76= driver.findElements(By.id("translateBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("translateBtn")){
        e.click();

      } }
    List<WebElement>all77= driver.findElements(By.id("customSelectBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("customSelectBtn")){
        e.click();

      } }
      List<WebElement>all78= driver.findElements(By.linkText("英语 » 中文"));
    for(WebElement e:all1){
      if(e.getText().equals("英语 » 中文")){
        e.click();

      } }
    List<WebElement>all79= driver.findElements(By.id("translateBtn"));
    for(WebElement e:all1){
      if(e.getText().equals("translateBtn")){
        e.click();

      } }
    List<WebElement>all80= driver.findElements(By.id("inputText"));
    for(WebElement e:all1){
      if(e.getText().equals("inputText")){
        e.click();

      } }
    List<WebElement>all81= driver.findElements(By.cssSelector(".item-clear"));
    for(WebElement e:all1){
      if(e.getText().equals(".item-clear")){
        e.click();

      } }

  }
}
