// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProjecttestingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void projecttesting() {
    driver.get("https://www.ownthink.com/robot.html");
    driver.manage().window().setSize(new Dimension(1552, 880));
    driver.findElement(By.cssSelector("input")).click();
    driver.findElement(By.cssSelector("input")).sendKeys("你好");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("你最近在干嘛");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("hello ");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("你能说英语吗");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("今天是几月份呢");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("几号？");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("今年是多少年啊？");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("你多少岁了？");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("你们的老板是谁呢");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("i want to ask your question");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("我知道你的问题了");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("所以你只能回答中文呢");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("input")).sendKeys("ok");
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".body")).click();
  }
}
